# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HoldemEngineService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='HoldemEngineService.proto',
  package='service.grpc',
  syntax='proto3',
  serialized_options=b'\n\014service.grpcP\001',
  serialized_pb=b'\n\x19HoldemEngineService.proto\x12\x0cservice.grpc\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"!\n\rSimpleMessage\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t2`\n\x1bSimpleHandManagementService\x12\x41\n\x05Hello\x12\x1b.service.grpc.SimpleMessage\x1a\x1b.service.grpc.SimpleMessageB\x10\n\x0cservice.grpcP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='service.grpc.SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='service.grpc.SimpleMessage.contents', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMESSAGE,
  '__module__' : 'HoldemEngineService_pb2'
  # @@protoc_insertion_point(class_scope:service.grpc.SimpleMessage)
  })
_sym_db.RegisterMessage(SimpleMessage)


DESCRIPTOR._options = None

_SIMPLEHANDMANAGEMENTSERVICE = _descriptor.ServiceDescriptor(
  name='SimpleHandManagementService',
  full_name='service.grpc.SimpleHandManagementService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=236,
  methods=[
  _descriptor.MethodDescriptor(
    name='Hello',
    full_name='service.grpc.SimpleHandManagementService.Hello',
    index=0,
    containing_service=None,
    input_type=_SIMPLEMESSAGE,
    output_type=_SIMPLEMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SIMPLEHANDMANAGEMENTSERVICE)

DESCRIPTOR.services_by_name['SimpleHandManagementService'] = _SIMPLEHANDMANAGEMENTSERVICE

# @@protoc_insertion_point(module_scope)
