# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TableService.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import Players_pb2 as Players__pb2
from . import Betting_pb2 as Betting__pb2
from . import Table_pb2 as Table__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TableService.proto',
  package='poker.proto',
  syntax='proto3',
  serialized_options=b'\n\013poker.protoP\001',
  serialized_pb=b'\n\x12TableService.proto\x12\x0bpoker.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\rPlayers.proto\x1a\rBetting.proto\x1a\x0bTable.proto\"G\n\rRequestStatus\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.poker.proto.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x0bTableUpdate\x12!\n\x05table\x18\x01 \x01(\x0b\x32\x12.poker.proto.Table\"%\n\rTableSettings\x12\x14\n\x0cjsonSettings\x18\x01 \x01(\t\"!\n\rSimpleMessage\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t* \n\nStatusCode\x12\x06\n\x02OK\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x32\xf6\x03\n\x14\x43\x61shGameTableService\x12@\n\x06\x63reate\x12\x1a.poker.proto.TableSettings\x1a\x1a.poker.proto.RequestStatus\x12?\n\tsubscribe\x12\x16.google.protobuf.Empty\x1a\x18.poker.proto.TableUpdate0\x01\x12;\n\x05start\x12\x16.google.protobuf.Empty\x1a\x1a.poker.proto.RequestStatus\x12:\n\x04stop\x12\x16.google.protobuf.Empty\x1a\x1a.poker.proto.RequestStatus\x12G\n\taddPlayer\x12\x1e.poker.proto.PlayerJoinRequest\x1a\x1a.poker.proto.RequestStatus\x12L\n\x0cremovePlayer\x12 .poker.proto.PlayerRemoveRequest\x1a\x1a.poker.proto.RequestStatus\x12K\n\ntakeAction\x12!.poker.proto.BettingActionRequest\x1a\x1a.poker.proto.RequestStatusB\x0f\n\x0bpoker.protoP\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,Players__pb2.DESCRIPTOR,Betting__pb2.DESCRIPTOR,Table__pb2.DESCRIPTOR,])

_STATUSCODE = _descriptor.EnumDescriptor(
  name='StatusCode',
  full_name='poker.proto.StatusCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILED', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=337,
  serialized_end=369,
)
_sym_db.RegisterEnumDescriptor(_STATUSCODE)

StatusCode = enum_type_wrapper.EnumTypeWrapper(_STATUSCODE)
OK = 0
FAILED = 1



_REQUESTSTATUS = _descriptor.Descriptor(
  name='RequestStatus',
  full_name='poker.proto.RequestStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='poker.proto.RequestStatus.code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='poker.proto.RequestStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=211,
)


_TABLEUPDATE = _descriptor.Descriptor(
  name='TableUpdate',
  full_name='poker.proto.TableUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='poker.proto.TableUpdate.table', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=261,
)


_TABLESETTINGS = _descriptor.Descriptor(
  name='TableSettings',
  full_name='poker.proto.TableSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonSettings', full_name='poker.proto.TableSettings.jsonSettings', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=300,
)


_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='poker.proto.SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contents', full_name='poker.proto.SimpleMessage.contents', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=335,
)

_REQUESTSTATUS.fields_by_name['code'].enum_type = _STATUSCODE
_TABLEUPDATE.fields_by_name['table'].message_type = Table__pb2._TABLE
DESCRIPTOR.message_types_by_name['RequestStatus'] = _REQUESTSTATUS
DESCRIPTOR.message_types_by_name['TableUpdate'] = _TABLEUPDATE
DESCRIPTOR.message_types_by_name['TableSettings'] = _TABLESETTINGS
DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
DESCRIPTOR.enum_types_by_name['StatusCode'] = _STATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestStatus = _reflection.GeneratedProtocolMessageType('RequestStatus', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTATUS,
  '__module__' : 'TableService_pb2'
  # @@protoc_insertion_point(class_scope:poker.proto.RequestStatus)
  })
_sym_db.RegisterMessage(RequestStatus)

TableUpdate = _reflection.GeneratedProtocolMessageType('TableUpdate', (_message.Message,), {
  'DESCRIPTOR' : _TABLEUPDATE,
  '__module__' : 'TableService_pb2'
  # @@protoc_insertion_point(class_scope:poker.proto.TableUpdate)
  })
_sym_db.RegisterMessage(TableUpdate)

TableSettings = _reflection.GeneratedProtocolMessageType('TableSettings', (_message.Message,), {
  'DESCRIPTOR' : _TABLESETTINGS,
  '__module__' : 'TableService_pb2'
  # @@protoc_insertion_point(class_scope:poker.proto.TableSettings)
  })
_sym_db.RegisterMessage(TableSettings)

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), {
  'DESCRIPTOR' : _SIMPLEMESSAGE,
  '__module__' : 'TableService_pb2'
  # @@protoc_insertion_point(class_scope:poker.proto.SimpleMessage)
  })
_sym_db.RegisterMessage(SimpleMessage)


DESCRIPTOR._options = None

_CASHGAMETABLESERVICE = _descriptor.ServiceDescriptor(
  name='CashGameTableService',
  full_name='poker.proto.CashGameTableService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=372,
  serialized_end=874,
  methods=[
  _descriptor.MethodDescriptor(
    name='create',
    full_name='poker.proto.CashGameTableService.create',
    index=0,
    containing_service=None,
    input_type=_TABLESETTINGS,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='subscribe',
    full_name='poker.proto.CashGameTableService.subscribe',
    index=1,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_TABLEUPDATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='start',
    full_name='poker.proto.CashGameTableService.start',
    index=2,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='stop',
    full_name='poker.proto.CashGameTableService.stop',
    index=3,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='addPlayer',
    full_name='poker.proto.CashGameTableService.addPlayer',
    index=4,
    containing_service=None,
    input_type=Players__pb2._PLAYERJOINREQUEST,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='removePlayer',
    full_name='poker.proto.CashGameTableService.removePlayer',
    index=5,
    containing_service=None,
    input_type=Players__pb2._PLAYERREMOVEREQUEST,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='takeAction',
    full_name='poker.proto.CashGameTableService.takeAction',
    index=6,
    containing_service=None,
    input_type=Betting__pb2._BETTINGACTIONREQUEST,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CASHGAMETABLESERVICE)

DESCRIPTOR.services_by_name['CashGameTableService'] = _CASHGAMETABLESERVICE

# @@protoc_insertion_point(module_scope)
